name: ml_workflow
on:
    push:
        branches:
            - main
        paths-ignore:
            - README.md

jobs:
    intregation:
        name: continuous integration
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v3
             
            - name: Lint code
              run: echo "Linting repository"

            - name: Run unit tests
              run: echo "Running unit tests"